# Generated by Django 4.0.5 on 2022-07-03 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ui', 'UI'), ('ux', 'UX'), ('en', 'Enhancement'), ('ft', 'Feature'), ('bg', 'Bug')], default='en', max_length=20)),
                ('upvotes', models.IntegerField()),
                ('status', models.CharField(choices=[('sg', 'Suggestion'), ('pl', 'Planned'), ('ip', 'In-progress')], default='sg', max_length=10)),
                ('description', models.TextField(max_length=400)),
                ('feedback_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
