# Generated by Django 4.0.6 on 2022-07-08 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='product_name',
            new_name='product',
        ),
    ]
