# Generated by Django 4.0.5 on 2022-07-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_owner',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
