# Generated by Django 4.0.6 on 2022-07-05 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_feedback_owner_feedback_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('ui', 'UI'), ('ux', 'UX'), ('enhancement', 'Enhancement'), ('feature', 'Feature'), ('bug', 'Bug')], default='en', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.product'),
        ),
    ]
