# Generated by Django 4.0.6 on 2022-07-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_feedback_category_alter_feedback_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('suggestion', 'Suggestion'), ('planned', 'Planned'), ('in-progress', 'In-progress')], default='sg', max_length=12),
        ),
    ]
